============================= test session starts ==============================
platform linux -- Python 3.9.1, pytest-6.2.2, py-1.10.0, pluggy-0.13.1 -- /usr/local/bin/python
cachedir: .pytest_cache
Using --random-order-bucket=global
Using --random-order-seed=940002

rootdir: /sandbox
plugins: cov-2.11.1, mock-3.5.1, random-order-1.0.4
collecting ... collected 5 items

test_doors.py::test_create_list_of_doors PASSED                          [ 20%]
test_doors.py::test_all_doors_are_false FAILED                           [ 40%]
test_doors.py::test_open_closed_door PASSED                              [ 60%]
test_doors.py::test_close_open_door PASSED                               [ 80%]
test_doors.py::test_create_default_door PASSED                           [100%]

=================================== FAILURES ===================================
___________________________ test_all_doors_are_false ___________________________

    def test_all_doors_are_false():
        door_list = DoorList(doors=3)
>       open_doors = sum(door_list)
E       TypeError: 'DoorList' object is not iterable

test_doors.py:23: TypeError
=========================== short test summary info ============================
FAILED test_doors.py::test_all_doors_are_false - TypeError: 'DoorList' object...
========================= 1 failed, 4 passed in 0.08s ==========================
